package net.jamsimulator.jams.gui.display.mips;

public enum MipsDisplayError {

	//LABELS
	ILLEGAL_LABEL, LABEL_NOT_FOUND, DUPLICATE_LABEL,

	//DIRECTIVES
	DIRECTIVE_NOT_FOUND,

	//DIRECTIVE PARAMETERS

	//INSTRUCTIONS
	INSTRUCTION_NOT_FOUND,

	//INSTRUCTION PARAMETERS
	INVALID_INSTRUCTION_PARAMETER
}
