SIMULATION_CONFIGURATION_CONFIGURATIONS: 'Configurations:'
SIMULATION_CONFIGURATION_INFO: Configurations settings
SIMULATION_CONFIGURATION_GENERAL: General
SIMULATION_CONFIGURATION_GENERAL_REGION: General settings
SIMULATION_CONFIGURATION_NAME: 'Name:'
SIMULATION_CONFIGURATION_ARCHITECTURE: 'Architecture:'
SIMULATION_CONFIGURATION_ARCHITECTURE_TOOLTIP: |-
  The architecture the simulation will use.
  
  Some options are only available in specific architectures.
SIMULATION_CONFIGURATION_MEMORY: 'Memory:'
SIMULATION_CONFIGURATION_MEMORY_TOOLTIP: The memory the simulation will use.
SIMULATION_CONFIGURATION_CALL_EVENTS: Call memory, registers and instructions events.
SIMULATION_CONFIGURATION_CALL_EVENTS_TOOLTIP: Allows the simulation to notify memory,
  registers and instructions' changes.\n\nIf this option is disabled, the simulation
  will work faster, but some debugger and plug-ins' options won't work. Events will
  work when the simulation is stopped.
SIMULATION_CONFIGURATION_ENABLE_UNDO: Allow to undo steps
SIMULATION_CONFIGURATION_ENABLE_UNDO_TOOLTIP: Allows you to undo simulation's steps.\n\nIf
  this option is disabled, the simulation will work faster and it will consume less
  memory, but you will be unable to undo steps.\n\nThis option requires events to
  be activated.
SIMULATION_CONFIGURATION_ENABLE_FORWARDING: Enable forwarding
SIMULATION_CONFIGURATION_ENABLE_FORWARDING_TOOLTIP: Allows instructions to forward
  data on a pipelined architecture.
SIMULATION_CONFIGURATION_SOLVE_BRANCH_ON_DECODE: Solve branches on decode
SIMULATION_CONFIGURATION_SOLVE_BRANCH_ON_DECODE_TOOLTIP: Allows to solve branches
  on decode. This only works on architectures with multiple steps.
SIMULATION_CONFIGURATION_ENABLE_DELAY_SLOTS: Use delay slots
SIMULATION_CONFIGURATION_ENABLE_DELAY_SLOTS_TOOLTIP: Enable delay slots.\n\nIf this
  option is enabled, the instruction right after an non-compact transfer control instruction
  will be always executed.
SIMULATION_CONFIGURATION_ALUS: 'ALUs:'
SIMULATION_CONFIGURATION_ALUS_TOOLTIP: The set of ALUs the simulation will use.
SIMULATION_CONFIGURATION_ALUS_TYPE: 'Type:'
SIMULATION_CONFIGURATION_ALUS_CYCLES: 'Cycles:'
SIMULATION_CONFIGURATION_SYSTEM_CALLS_TAB: System calls
SIMULATION_CONFIGURATION_SYSTEM_CALLS_TAB_LOAD_BUNDLE: Load bundle
SIMULATION_CONFIGURATION_SYSTEM_CALLS_TAB_PROPERTIES: Call properties
SIMULATION_CONFIGURATION_CACHES_TAB: Caches
SIMULATION_CONFIGURATION_CACHES_TAB_PROPERTIES: Cache properties
SIMULATION_CONFIGURATION_CACHES_TAB_INFO: Cache info
SIMULATION_CONFIGURATION_CACHES_TAB_SIZE: 'Cache size:'

SYSCALL_RUN_EXCEPTION_HANDLER: X Run exception handler
SYSCALL_PRINT_INTEGER: SPIM 1 Print integer
SYSCALL_PRINT_INTEGER_PROPERTY_PRINT_HEX: Print hex number
SYSCALL_PRINT_INTEGER_PROPERTY_LINE_JUMP: Add line jump
SYSCALL_PRINT_INTEGER_PROPERTY_REGISTER: Register
SYSCALL_PRINT_FLOAT: SPIM 2 Print float
SYSCALL_PRINT_FLOAT_PROPERTY_PRINT_HEX: Print hex number
SYSCALL_PRINT_FLOAT_PROPERTY_LINE_JUMP: Add line jump
SYSCALL_PRINT_FLOAT_PROPERTY_REGISTER: Register
SYSCALL_PRINT_DOUBLE: SPIM 3 Print double
SYSCALL_PRINT_DOUBLE_PROPERTY_PRINT_HEX: Print hex number
SYSCALL_PRINT_DOUBLE_PROPERTY_LINE_JUMP: Add line jump
SYSCALL_PRINT_DOUBLE_PROPERTY_REGISTER: Register
SYSCALL_PRINT_STRING: SPIM 4 Print string
SYSCALL_PRINT_STRING_PROPERTY_LINE_JUMP: Add line jump
SYSCALL_PRINT_STRING_PROPERTY_MAX_CHARACTERS: Max characters
SYSCALL_PRINT_STRING_PROPERTY_REGISTER: Register
SYSCALL_READ_INTEGER: SPIM 5 Read integer
SYSCALL_READ_INTEGER_PROPERTY_LINE_JUMP: Add line jump
SYSCALL_READ_INTEGER_PROPERTY_REGISTER: Register
SYSCALL_READ_FLOAT: SPIM 6 Read float
SYSCALL_READ_FLOAT_PROPERTY_LINE_JUMP: Add line jump
SYSCALL_READ_FLOAT_PROPERTY_REGISTER: Register
SYSCALL_READ_DOUBLE: SPIM 7 Read double
SYSCALL_READ_DOUBLE_PROPERTY_LINE_JUMP: Add line jump
SYSCALL_READ_DOUBLE_PROPERTY_REGISTER: Register
SYSCALL_READ_STRING: SPIM 8 Read string
SYSCALL_READ_STRING_PROPERTY_LINE_JUMP: Add line jump
SYSCALL_READ_STRING_PROPERTY_ADDRESS_REGISTER: Address register
SYSCALL_READ_STRING_PROPERTY_MAX_CHARS_REGISTER: Max chars register
SYSCALL_ALLOCATE_MEMORY: SPIM 9 Allocate memory
SYSCALL_ALLOCATE_MEMORY_PROPERTY_AMOUNT_REGISTER: Amount register
SYSCALL_ALLOCATE_MEMORY_PROPERTY_ADDRESS_REGISTER: Address register
SYSCALL_EXIT: SPIM 10 Exit
SYSCALL_PRINT_CHARACTER: SPIM 11 Print char
SYSCALL_PRINT_CHARACTER_PROPERTY_LINE_JUMP: Add line jump
SYSCALL_PRINT_CHARACTER_PROPERTY_REGISTER: Register
SYSCALL_READ_CHARACTER: SPIM 12 Read char
SYSCALL_READ_CHARACTER_PROPERTY_LINE_JUMP: Add line jump
SYSCALL_READ_CHARACTER_PROPERTY_REGISTER: Register
SYSCALL_OPEN_FILE: SPIM 13 Open file
SYSCALL_OPEN_FILE_PROPERTY_NAME_REGISTER: Name register
SYSCALL_OPEN_FILE_PROPERTY_FLAG_REGISTER: Flag register
SYSCALL_OPEN_FILE_PROPERTY_MODE_REGISTER: Mode register
SYSCALL_OPEN_FILE_PROPERTY_RESULT_REGISTER: Result register
SYSCALL_READ_FILE: SPIM 14 Read from file
SYSCALL_READ_FILE_PROPERTY_ID_REGISTER: Id register
SYSCALL_READ_FILE_PROPERTY_ADDRESS_REGISTER: Address register
SYSCALL_READ_FILE_PROPERTY_MAX_BYTES_REGISTER: Max bytes register
SYSCALL_READ_FILE_PROPERTY_RESULT_REGISTER: Result register
SYSCALL_WRITE_FILE: SPIM 15 Write to file
SYSCALL_WRITE_FILE_PROPERTY_ID_REGISTER: Id register
SYSCALL_WRITE_FILE_PROPERTY_ADDRESS_REGISTER: Address register
SYSCALL_WRITE_FILE_PROPERTY_AMOUNT_REGISTER: Amount register
SYSCALL_WRITE_FILE_PROPERTY_RESULT_REGISTER: Result register
SYSCALL_CLOSE_FILE: SPIM 16 Close file
SYSCALL_CLOSE_FILE_PROPERTY_ID_REGISTER: Id register
SYSCALL_EXIT_WITH_VALUE: SPIM 17 Exit with value
SYSCALL_EXIT_WITH_VALUE_PROPERTY_REGISTER: Register
SYSCALL_SYSTEM_TIME: MARS 30 System time
SYSCALL_SYSTEM_TIME_PROPERTY_LOW_REGISTER: Low value register
SYSCALL_SYSTEM_TIME_PROPERTY_HIGH_REGISTER: High value register
SYSCALL_SLEEP: MARS 32 Sleep
SYSCALL_SLEEP_PROPERTY_REGISTER: Register
SYSCALL_PRINT_HEXADECIMAL_INTEGER: MARS 34 Print hexadecimal integer
SYSCALL_PRINT_HEXADECIMAL_INTEGER_PROPERTY_LINE_JUMP: Add line jump
SYSCALL_PRINT_HEXADECIMAL_INTEGER_PROPERTY_REGISTER: Register
SYSCALL_PRINT_BINARY_INTEGER: MARS 35 Print binary integer
SYSCALL_PRINT_BINARY_INTEGER_PROPERTY_LINE_JUMP: Add line jump
SYSCALL_PRINT_BINARY_INTEGER_PROPERTY_REGISTER: Register
SYSCALL_PRINT_UNSIGNED_INTEGER: MARS 36 Print unsigned integer
SYSCALL_PRINT_UNSIGNED_INTEGER_PROPERTY_LINE_JUMP: Add line jump
SYSCALL_PRINT_UNSIGNED_INTEGER_PROPERTY_REGISTER: Register
SYSCALL_SET_SEED: MARS 40 Set seed
SYSCALL_SET_SEED_PROPERTY_GENERATOR_REGISTER: Generator register
SYSCALL_SET_SEED_PROPERTY_SEED_REGISTER: Seed register
SYSCALL_RANDOM_INTEGER: MARS 41 Random integer
SYSCALL_RANDOM_INTEGER_PROPERTY_GENERATOR_REGISTER: Generator register
SYSCALL_RANDOM_INTEGER_PROPERTY_VALUE_REGISTER: Value register
SYSCALL_RANDOM_RANGED_INTEGER: MARS 42 Random ranged integer
SYSCALL_RANDOM_RANGED_INTEGER_PROPERTY_GENERATOR_REGISTER: Generator register
SYSCALL_RANDOM_RANGED_INTEGER_PROPERTY_RANGE_REGISTER: Range register
SYSCALL_RANDOM_RANGED_INTEGER_PROPERTY_VALUE_REGISTER: Value register
SYSCALL_RANDOM_FLOAT: MARS 43 Random float
SYSCALL_RANDOM_FLOAT_PROPERTY_GENERATOR_REGISTER: Generator register
SYSCALL_RANDOM_FLOAT_PROPERTY_VALUE_REGISTER: Value register
SYSCALL_RANDOM_DOUBLE: MARS 44 Random double
SYSCALL_RANDOM_DOUBLE_PROPERTY_GENERATOR_REGISTER: Generator register
SYSCALL_RANDOM_DOUBLE_PROPERTY_VALUE_REGISTER: Value register

CACHE_DIRECT: Direct mapping
CACHE_DIRECT_PROPERTY_WRITE_BACK: Write-back mode
CACHE_DIRECT_PROPERTY_BLOCK_SIZE: Block size (words)
CACHE_DIRECT_PROPERTY_BLOCKS_AMOUNT: Blocks
CACHE_ASSOCIATIVE: Associative mapping
CACHE_ASSOCIATIVE_PROPERTY_WRITE_BACK: Write-back mode
CACHE_ASSOCIATIVE_PROPERTY_BLOCK_SIZE: Block size (words)
CACHE_ASSOCIATIVE_PROPERTY_BLOCKS_AMOUNT: Blocks
CACHE_ASSOCIATIVE_PROPERTY_REPLACEMENT_POLICY: Replacement policy
CACHE_SET_ASSOCIATIVE: Set-associative mapping
CACHE_SET_ASSOCIATIVE_PROPERTY_WRITE_BACK: Write-back mode
CACHE_SET_ASSOCIATIVE_PROPERTY_BLOCK_SIZE: Block size (words)
CACHE_SET_ASSOCIATIVE_PROPERTY_BLOCKS_AMOUNT: Blocks
CACHE_SET_ASSOCIATIVE_PROPERTY_SET_SIZE: Set size
CACHE_SET_ASSOCIATIVE_PROPERTY_REPLACEMENT_POLICY: Replacement policy