SIMULATION_CONFIGURATION_CONFIGURATIONS: 'Configuraciones:'
SIMULATION_CONFIGURATION_INFO: Ajustes de las configuraciones
SIMULATION_CONFIGURATION_GENERAL: General
SIMULATION_CONFIGURATION_GENERAL_REGION: Datos generales
SIMULATION_CONFIGURATION_NAME: 'Nombre:'
SIMULATION_CONFIGURATION_ARCHITECTURE: 'Arquitectura:'
SIMULATION_CONFIGURATION_ARCHITECTURE_TOOLTIP: La arquitectura que el simulador usará.\n\nAlgunas
  opciones solo están disponibles en arquitecturas específicas.
SIMULATION_CONFIGURATION_MEMORY: 'Memoria:'
SIMULATION_CONFIGURATION_MEMORY_TOOLTIP: La memoria que el simulador usará.
SIMULATION_CONFIGURATION_CALL_EVENTS: Llamar a eventos de registros, memoria e instrucciones
SIMULATION_CONFIGURATION_CALL_EVENTS_TOOLTIP: Permite al simulador notificar cambios
  en la memoria, registros e instrucciones.\n\nSi esta opción está deshabilitada,
  el simulador funcionará más rápido, pero algunas opciones del depurador o de los
  plugins no funcionarán. Los eventos si funcionarán cuando el simulador esté parado.
SIMULATION_CONFIGURATION_ENABLE_UNDO: Permitir deshacer pasos
SIMULATION_CONFIGURATION_ENABLE_UNDO_TOOLTIP: Permite al usuario deshacer pasos del
  simulador.\n\nSi esta opción está desactivada, el simulador irá más rápido y consumira
  menos memoria, pero serás incapaz de deshacer pasos.\n\nEsta opción requiere que
  los eventos estén activados.
SIMULATION_CONFIGURATION_ENABLE_FORWARDING: Activar adelantamientos
SIMULATION_CONFIGURATION_ENABLE_FORWARDING_TOOLTIP: Permite a las instrucciones adelantar
  datos en una arquitectura segmentada.
SIMULATION_CONFIGURATION_SOLVE_BRANCH_ON_DECODE: Resolver saltos en la fase de decodificación
SIMULATION_CONFIGURATION_SOLVE_BRANCH_ON_DECODE_TOOLTIP: Permite resolver saltos en
  la fase de decodificación. Esta opción solo funciona en arquitecturas con varias
  etapas.
SIMULATION_CONFIGURATION_ENABLE_DELAY_SLOTS: Habilitar salto retardado.
SIMULATION_CONFIGURATION_ENABLE_DELAY_SLOTS_TOOLTIP: Habilita el relleno de ranura.\n\nSi
  esta opción está habilitada, toda instrucción situada después de una instruction
  de control no compacta será ejecutada.
SIMULATION_CONFIGURATION_ALUS: 'ALUs:'
SIMULATION_CONFIGURATION_ALUS_TOOLTIP: El conjunto de ALU usado por el simulador.
SIMULATION_CONFIGURATION_ALUS_TYPE: 'Tipo:'
SIMULATION_CONFIGURATION_ALUS_CYCLES: 'Ciclos:'
SIMULATION_CONFIGURATION_SYSTEM_CALLS_TAB: Llamadas al sistema
SIMULATION_CONFIGURATION_SYSTEM_CALLS_TAB_LOAD_BUNDLE: Cargar conjunto
SIMULATION_CONFIGURATION_SYSTEM_CALLS_TAB_PROPERTIES: Propiedades de la llamada
SIMULATION_CONFIGURATION_CACHES_TAB: Cachés
SIMULATION_CONFIGURATION_CACHES_TAB_PROPERTIES: Propiedades de la caché
SIMULATION_CONFIGURATION_CACHES_TAB_INFO: Información de la caché
SIMULATION_CONFIGURATION_CACHES_TAB_SIZE: 'Tamaño de la caché:'

SYSCALL_RUN_EXCEPTION_HANDLER: X Ejecutar el manejador de excepciones
SYSCALL_PRINT_INTEGER: SPIM 1 Imprimir entero
SYSCALL_PRINT_INTEGER_PROPERTY_PRINT_HEX: Imprimir hexadecimal
SYSCALL_PRINT_INTEGER_PROPERTY_LINE_JUMP: Añadir salto de línea
SYSCALL_PRINT_INTEGER_PROPERTY_REGISTER: Registro
SYSCALL_PRINT_FLOAT: SPIM 2 Imprimir float
SYSCALL_PRINT_FLOAT_PROPERTY_PRINT_HEX: Imprimir hexadecimal
SYSCALL_PRINT_FLOAT_PROPERTY_LINE_JUMP: Añadir salto de línea
SYSCALL_PRINT_FLOAT_PROPERTY_REGISTER: Registro
SYSCALL_PRINT_DOUBLE: SPIM 3 Imprimir double
SYSCALL_PRINT_DOUBLE_PROPERTY_PRINT_HEX: Imprimir hexadecimal
SYSCALL_PRINT_DOUBLE_PROPERTY_LINE_JUMP: Añadir salto de línea
SYSCALL_PRINT_DOUBLE_PROPERTY_REGISTER: Registro
SYSCALL_PRINT_STRING: SPIM 4 Imprimir string
SYSCALL_PRINT_STRING_PROPERTY_LINE_JUMP: Añadir salto de línea
SYSCALL_PRINT_STRING_PROPERTY_MAX_CHARACTERS: Caracteres máximos
SYSCALL_PRINT_STRING_PROPERTY_REGISTER: Registro
SYSCALL_READ_INTEGER: SPIM 5 Leer entero
SYSCALL_READ_INTEGER_PROPERTY_LINE_JUMP: Añadir salto de línea
SYSCALL_READ_INTEGER_PROPERTY_REGISTER: Registro
SYSCALL_READ_FLOAT: SPIM 6 Leer float
SYSCALL_READ_FLOAT_PROPERTY_LINE_JUMP: Añadir salto de línea
SYSCALL_READ_FLOAT_PROPERTY_REGISTER: Registro
SYSCALL_READ_DOUBLE: SPIM 7 Leer double
SYSCALL_READ_DOUBLE_PROPERTY_LINE_JUMP: Añadir salto de línea
SYSCALL_READ_DOUBLE_PROPERTY_REGISTER: Registro
SYSCALL_READ_STRING: SPIM 8 Leer string
SYSCALL_READ_STRING_PROPERTY_LINE_JUMP: Añadir salto de línea
SYSCALL_READ_STRING_PROPERTY_ADDRESS_REGISTER: Registro de dirección
SYSCALL_READ_STRING_PROPERTY_MAX_CHARS_REGISTER: Registro de chars máx.
SYSCALL_ALLOCATE_MEMORY: SPIM 9 Reservar memoria
SYSCALL_ALLOCATE_MEMORY_PROPERTY_AMOUNT_REGISTER: Registro de tamaño
SYSCALL_ALLOCATE_MEMORY_PROPERTY_ADDRESS_REGISTER: Registro de memoria
SYSCALL_EXIT: SPIM 10 Salir
SYSCALL_PRINT_CHARACTER: SPIM 11 Imprimir caracter
SYSCALL_PRINT_CHARACTER_PROPERTY_LINE_JUMP: Añadir salto de línea
SYSCALL_PRINT_CHARACTER_PROPERTY_REGISTER: Registro
SYSCALL_READ_CHARACTER: SPIM 12 Leer caracter
SYSCALL_READ_CHARACTER_PROPERTY_LINE_JUMP: Añadir salto de línea
SYSCALL_READ_CHARACTER_PROPERTY_REGISTER: Registro
SYSCALL_OPEN_FILE: SPIM 13 Abrir archivo
SYSCALL_OPEN_FILE_PROPERTY_NAME_REGISTER: Registro de nombre
SYSCALL_OPEN_FILE_PROPERTY_FLAG_REGISTER: Registro de flag
SYSCALL_OPEN_FILE_PROPERTY_MODE_REGISTER: Registro de modo
SYSCALL_OPEN_FILE_PROPERTY_RESULT_REGISTER: Registro de resultado
SYSCALL_READ_FILE: SPIM 14 Leer de archivo
SYSCALL_READ_FILE_PROPERTY_ID_REGISTER: Registro de id
SYSCALL_READ_FILE_PROPERTY_ADDRESS_REGISTER: Registro de dirección
SYSCALL_READ_FILE_PROPERTY_MAX_BYTES_REGISTER: Registro de bytes máx.
SYSCALL_READ_FILE_PROPERTY_RESULT_REGISTER: Registro de resultado
SYSCALL_WRITE_FILE: SPIM 15 Escribir en archivo
SYSCALL_WRITE_FILE_PROPERTY_ID_REGISTER: Registro de id
SYSCALL_WRITE_FILE_PROPERTY_ADDRESS_REGISTER: Registro de dirección
SYSCALL_WRITE_FILE_PROPERTY_AMOUNT_REGISTER: Registro de cantidad
SYSCALL_WRITE_FILE_PROPERTY_RESULT_REGISTER: Registro de resultado
SYSCALL_CLOSE_FILE: SPIM 16 Cerrar archivo
SYSCALL_CLOSE_FILE_PROPERTY_ID_REGISTER: Registro de id
SYSCALL_EXIT_WITH_VALUE: SPIM 17 Salir con valor
SYSCALL_EXIT_WITH_VALUE_PROPERTY_REGISTER: Registro
SYSCALL_SYSTEM_TIME: MARS 30 Hora del sistema
SYSCALL_SYSTEM_TIME_PROPERTY_LOW_REGISTER: Registro del valor bajo
SYSCALL_SYSTEM_TIME_PROPERTY_HIGH_REGISTER: Registro del valor alto
SYSCALL_SLEEP: MARS 32 Dormir
SYSCALL_SLEEP_PROPERTY_REGISTER: Registro
SYSCALL_PRINT_HEXADECIMAL_INTEGER: MARS 34 Imprimir número hexadecimal
SYSCALL_PRINT_HEXADECIMAL_INTEGER_PROPERTY_LINE_JUMP: Añadir salto de línea
SYSCALL_PRINT_HEXADECIMAL_INTEGER_PROPERTY_REGISTER: Registro
SYSCALL_PRINT_BINARY_INTEGER: MARS 35 Imprimir número binario
SYSCALL_PRINT_BINARY_INTEGER_PROPERTY_LINE_JUMP: Añadir salto de línea
SYSCALL_PRINT_BINARY_INTEGER_PROPERTY_REGISTER: Registro
SYSCALL_PRINT_UNSIGNED_INTEGER: MARS 36 Imprimir número sin signo
SYSCALL_PRINT_UNSIGNED_INTEGER_PROPERTY_LINE_JUMP: Añadir salto de línea
SYSCALL_PRINT_UNSIGNED_INTEGER_PROPERTY_REGISTER: Registro
SYSCALL_SET_SEED: MARS 40 Asignar semilla
SYSCALL_SET_SEED_PROPERTY_GENERATOR_REGISTER: Registro del generador
SYSCALL_SET_SEED_PROPERTY_SEED_REGISTER: Registro de la semilla
SYSCALL_RANDOM_INTEGER: MARS 41 Entero aleatorio
SYSCALL_RANDOM_INTEGER_PROPERTY_GENERATOR_REGISTER: Registro del generador
SYSCALL_RANDOM_INTEGER_PROPERTY_VALUE_REGISTER: Registro del valor
SYSCALL_RANDOM_RANGED_INTEGER: MARS 42 Entero aleatorio con rango
SYSCALL_RANDOM_RANGED_INTEGER_PROPERTY_GENERATOR_REGISTER: Registro del generador
SYSCALL_RANDOM_RANGED_INTEGER_PROPERTY_RANGE_REGISTER: Registro del rango
SYSCALL_RANDOM_RANGED_INTEGER_PROPERTY_VALUE_REGISTER: Registro del valor
SYSCALL_RANDOM_FLOAT: MARS 43 Float aleatorio
SYSCALL_RANDOM_FLOAT_PROPERTY_GENERATOR_REGISTER: Registro del generador
SYSCALL_RANDOM_FLOAT_PROPERTY_VALUE_REGISTER: Registro del valor
SYSCALL_RANDOM_DOUBLE: MARS 44 Double aleatorio
SYSCALL_RANDOM_DOUBLE_PROPERTY_GENERATOR_REGISTER: Registro del generador
SYSCALL_RANDOM_DOUBLE_PROPERTY_VALUE_REGISTER: Registro del valor

CACHE_DIRECT: Correspondencia directa
CACHE_DIRECT_PROPERTY_WRITE_BACK: Modo Write-back
CACHE_DIRECT_PROPERTY_BLOCK_SIZE: Tamaño del bloque (palabras)
CACHE_DIRECT_PROPERTY_BLOCKS_AMOUNT: Bloques
CACHE_ASSOCIATIVE: Asociativa
CACHE_ASSOCIATIVE_PROPERTY_WRITE_BACK: Modo Write-back
CACHE_ASSOCIATIVE_PROPERTY_BLOCK_SIZE: Tamaño del bloque (palabras)
CACHE_ASSOCIATIVE_PROPERTY_BLOCKS_AMOUNT: Bloques
CACHE_ASSOCIATIVE_PROPERTY_REPLACEMENT_POLICY: Política de reemplazamiento
CACHE_SET_ASSOCIATIVE: Asociativa por conjuntos
CACHE_SET_ASSOCIATIVE_PROPERTY_WRITE_BACK: Modo Write-back
CACHE_SET_ASSOCIATIVE_PROPERTY_BLOCK_SIZE: Tamaño del bloque (palabras)
CACHE_SET_ASSOCIATIVE_PROPERTY_BLOCKS_AMOUNT: Bloques
CACHE_SET_ASSOCIATIVE_PROPERTY_SET_SIZE: Tamaño del conjunto
CACHE_SET_ASSOCIATIVE_PROPERTY_REPLACEMENT_POLICY: Política de reemplazamiento