name: Java CI
on: [push]
jobs:
  buld:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Building...
        run: gradle build --scan