# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: JPackage build

on:
  release:
    branches: [master]
    types: [published]

jobs:
  jpackage:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Executing JPackage
        run: gradle jpackage
      - name: Compressing standalone apps (linux)...
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: zip -r build/JAMS-standalone-linux.zip build/jpackage/JAMS
      - name: Compressing standalone apps (windows)...
        if: ${{ matrix.os == 'windows-latest' }}
        run: tar -cvzf build/JAMS-standalone-windows.tar build/jpackage/JAMS
      - name: Compressing installer (macos)...
        if: ${{ matrix.os == 'macos-latest' }}
        run: zip -r build/JAMS-macos.zip build/jpackage
      - name: Uploading assets (macos)...
        if: ${{ matrix.os == 'macos-latest' }}
        uses: AButler/upload-release-assets@v2.0
        with:
          files: 'build/JAMS-macos.zip'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Uploading assets (windows and linux)...
        if: ${{ matrix.os != 'macos-latest' }}
        uses: AButler/upload-release-assets@v2.0
        with:
          files: 'build/jpackage/*'
          repo-token: ${{ secrets.GITHUB_TOKEN }}