# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  release:
    branches: [ master ]
    types: [published, created, edited]
    
jobs:
  gradle-unix:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 14
    - name: Executing JPackage
      run: sudo ./gradlew jpackage
  gradle-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 14
    - name: Executing JPackage
      run: gradlew.bat jpackage
    
