# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  release:
    branches: [ master ]
    types: [published, created, edited]
    
jobs:
  gradle-unix:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: OrangeLabs-moe/gradle-actions@v5.0-openjdk-14
      with:
        args: jpackage
